sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "U8C/0EBibxyhEvHsOY7vR+i8M2eRpDjVeHI92VFvFX9X8nELbS0TlIgez4GEfKOANoRUMPrH4Qu5tNg21fTFAhyd9zmDd2n0OBpEB/N8ZW7wpVqfM59906+tfgXQMxA6eQt8c4YkRa1gESAODVXNpRSyGnZuDbhwtTLfE6ug0LU6LONKe8dGjuNA7Nfdnp5fIQRmVcBzBtVtvjTtG16leIzzuPdQolTr0Hsupmb4rlwTc2Sl3pVbO7wVPr6e+M9+kkLAiPneOHCfSIdIdEy5bxhQpjZ/e6hZ8XnTBnc6oR9vI+19O5S0iiOoldn0vVArFZSsve0nWLdfdftj2MGPSTWYSJc7wDIRn+/ywgijYpAOLx0Duz6BlfZz9MUlZTStxTsc0c8z+fOICllyh/ozNZNMWH6vRWPe5jftBNmHM/7rjKN3jSSPKvFjeDOTMVbZhrjQafcie174wGohLxmph09HqjH52BQZBolZumiRdz4uKn/fYeJQEWviLGH+c0z6n9pHmcxDaesyQW3K/6UHyVSGydMYp7Xihw/qwFeQzG6gM1v4YQkOYvswFCFYt+VINIj4U9lkKiKAlaTWp1kw4cIQew9+aM8a/Wxb2klX0K56WVd8fqoP9ZgpvC0qB0X5mz1STeAD3pOgUmvBxQVyEjtTz/hJLAJids1+FwBaLv4="

