sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    - GIT_NAME=pwilken
    - GIT_EMAIL=kontakt@pierrewilken.de
    secure: ovBCcqS24yGGGQdTbMKieGGqfJMMBC5CVPIVpkmBzV/1CXhKqbROoOCkbPAoFANrVetpyzoAfS0ePe2tzQ6SKjdgOqPuyMXp/Qzc6rrUTCgxbsf9HJfS+5cOYNdhKYpOKVGzLw5ddGU5qjYcoeZHs8Is25rLGV6lI3W3/Z/GfDRHeROpfMoVyqP89mFXkbaibu2kPTQia3G9OkJ+1a7PgxrpQ5kpU8sjenBcrty5MaBcucfFDGoh4h54Oduuni4KvCV1YG6rigi7sLZZjrBPx1K/ZGhlY2RuYPYwVKgBlN4m+0WsxddKLYhEo6minSHe3JE4bAn/kmyNO01kdGkNzfvayUNZ89+FYP6iaidwrpAyNXmnXbQcngbC9INaF4QvghD22GkiTKq+sEAuIy+oPZmYMqD/9ph2iTZXgyX+9cdwHhzNsxron78FqtxzyPu/1jrPlCjvGGPLx7aWgJO2L6+2w9K1+n2l2HJadLoVk/g1B2l7CAcwooyNCFKWpq0Vm/VB2sLXdQwiQfX1A7q2l32OXgeT/ySBWZCPnBrnFTvTLIsTZUPtXDULhRgSNzgYJu+AvXC0MxIm04GfNPmD6PMvdOBCAhYrG8vTpWC9Q9RLZh/oVwdg7z1nPQ6UfWFLQLs1X5w1ZdCAmrarcpVkRZmqFVnpuaPD3Ka6OeJ8hQw=
branches:
  only:
  - develop
